# Generated by Django 4.2.1 on 2023-05-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_country_category_tiket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='text',
            new_name='description',
        ),
    ]
