# Generated by Django 4.2.1 on 2023-05-29 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_text_country_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTikets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('baggage', models.TextField()),
                ('hand_luggage', models.TextField()),
                ('nutrtion', models.BooleanField()),
                ('exchange_return', models.BooleanField()),
                ('preferred_seat_selection', models.BooleanField()),
                ('business_lounge', models.BooleanField()),
                ('separate_landing', models.BooleanField()),
                ('separate_reception_desk', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='tiket',
            old_name='arrival_place',
            new_name='arrival',
        ),
        migrations.RenameField(
            model_name='tiket',
            old_name='departure_place',
            new_name='departure',
        ),
        migrations.RenameField(
            model_name='tiket',
            old_name='title',
            new_name='flight_name',
        ),
        migrations.RenameField(
            model_name='tiket',
            old_name='description',
            new_name='flight_time',
        ),
        migrations.AddField(
            model_name='tiket',
            name='arrival_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiket',
            name='departure_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiket',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_tikets', to='main.categorytikets'),
            preserve_default=False,
        ),
    ]
