# Generated by Django 4.2.1 on 2023-06-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_categorytikets_rename_arrival_place_tiket_arrival_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiket',
            name='departure',
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
