# Generated by Django 4.2.1 on 2023-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.IntegerField(default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cardholder_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cvv',
            field=models.IntegerField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='mail',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='validity',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
